### ISSUE TITLE
JavaScript refresher + Typescript

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/anlq-vue#1]
- JavaScript refresher
  - https://github.com/zinza-d2-training/new-to-react/blob/fresher/01_Day_JavaScript_Refresher/01_javascript_refresher.md

- Tìm hiểu về Typescript
  - [Object reference and cloning](https://javascript.info/object-copy)
  - [Default Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
  - [Interface/Type](https://www.typescriptlang.org/docs/handbook/2/objects.html)
  - [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)
  - [Class](https://www.typescriptlang.org/docs/handbook/2/classes.html)
  - [Advanced Type](https://www.typescriptlang.org/docs/handbook/utility-types.html)

- Bài tập
  - Clone object đã cho, sử dụng spread và destructing. Yêu cầu object và thuộc tính của object đã cloned không có reference tới object cũ [Link](https://codesandbox.io/s/spread-operator-destructing-object-cloning-rjmcy?file=/src/index.js)
  - Viết Model type cho các table database 

![covidtracker](https://user-images.githubusercontent.com/61738572/150733206-6ca87af2-86f0-464e-94b3-ef651c925930.png)

  - Sử dụng các advanced type để viết interface Scalars đại diện cho các kiểu dữ liệu của DB (Ví dụ: Int => number, varchar => string)
  - Sử dụng Scalars để thay thế các type cho model ở trên. Viết các type InsertInput (create api), SetInput (update api) kế thừa từ các model trên. (Ví dụ VaccineInsertInput, VaccineSetInput)

  - Mẫu đã làm [Link](https://www.typescriptlang.org/play#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3IG4AoGgS2OAgCcAzOAY2gGVO5ycFgGcoAbxpQpUAJJMAXCVIBbZCwA0k6WkYhGwRWVWtN0qABEA9qUTkIhlWtPSAYuUtwDS4xq1SdyhDCwHDKYIrBLIwA5s5S5p4QwPSBEcBRxNF+eBAAHl6RMXFQAGpCnAAWQmkZsdkJzDVF2QH2UIWZNAC+dPqsHNx4KUEhYS70EOQAJqISZpwsEIlTAPqeinwCQsIA2gDkrcGhYHsAusWkYFPLa16bgiL7h6Mn5929TP1c0ADCi8sAVWErHGkxm4myCyWzFWiBAAH5FPAkKh7tt9nJgGcMMUoTc4StSMCWIjYAhkCggawce8GJ92N8oAAhODA0HTUR5ZjEcHPY7smbqKB-aEQKZUlgC2Y9OnMBmDMqcTiMaBciA80QstkTDkQsz0KYbfgPXZ7TFnYrEUJtNGPPZlFiVIQW7JwUjACqWKIALzFRq2dp0xD0TBdZjYLEsyjW0RtxvRZtDbzMwEsMYgpORFNtpvNpxpZmEnuAwn9JoxSeKRcsJZWU3oR2I3Ez5NR8bteYL0jYFHIIBWADcuMqrTCywm85oZaBIKVhyq5MTgHIwO6cFAAAr0TgAaxQipHECFewNe0IUD2VsCZ6IezdHq99F9UxvF4jUfTr72qc-5721ZLL8AOEOsGxCJsIC-HtKH7IclUYZY9gwWgZ2gA8VR4JIVzXXANyEZIBEpYlF1YZdiFXYAMA+OUBl+awmBYEAoDVDVmVZCApT1aQDXHDtK2yK84wDU0HSdFgw2kOCR08ehLGIUs53g0dZOIHZTlpVDhXo9IQBIlgyIo9ct13FAfm0xjj1PP9BKQlDwDo0gGJATCDJwzd8PoQizMcnS9NcyjqK+BV52UuTmPydVwS1DidXBOZuMNKAcwrLFk2kThzP7HikvbXN+LMKSELHHLhJSiSpGgvtBxC5ZeLy1LcUyxRvKcqc6E09DQuIPzsOAIztz3TqZLkyyXz-DKfMYlYrNvQrRzFKDe1gmqYVsmgOpWlSXN6oyPMIobkjknryPdKjZSC352PC7kovYzj4qkbLksTBrsmuRoSvLA5hiOMJyqgCanOmxLnsnSF2IU0H8ukKZoQqSHcrKtKpEBnTmsytr1vs4V2OOwzcIG0z2NGr93sg8bMuBr9+GBYRSbhunkKx2cfnY7aTr63C9vIIngTx07AvlaAJWuyLNTu2LZmyJ7EZe-62HoERgBWQS6v2USqnE5GoEEYIVetNX7XKTX-ogZQ4HochDY151tbAVlhAAdy9EHZZtrXMc0iV+c5zdCYlEm-wVpX9evP9deVmy-zNi3yC-e3hCdl21q94l2fx9z9M8nnvfk0jeqoqQgA)

**Comment by quanganzinza** [comment]
Bài tập 
- https://codesandbox.io/s/spread-operator-destructing-object-cloning-forked-di9f39?file=/src/index.js

- Model type [Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3IG4AoGgS2OAgCcAzOAY2gGVO5ycFgGcoAbxpQpUAJIA5NAC4SpALbIWAGknS08gJrylK9a23SoANQCCAJQDCACTvLhwFowDm53TJgBRHjRrGAAFV3cvGgBfOkZmdi5oNHpVCDc4VTAAMXoIcgATcWkdKU4WCDhmAoB9KoB+ZXgkVD4BIWEAbQByPQCgkNDugF0MHylSMAKqiFqGpoRkFDbBER6+wOCwkbGYuKZWDm4oewqZgoBVYVZc-IKJC3LK6prEEEbYRdb+Va7uox24ygT3OrxANVI1xYH2aSyurF2sQYB0SxwAQnBrrdClAIAAPZjEAqiFJpDJZbEFTQnM7VeEsSniJHxQ5JKD03EEiBE0QYrF5HEPaT0ArKFYdHoA4ZAtj0ETAGrETIQMU-CXdGwOZy2EZAwRuRXK1XtNYauxOOy60q41RwejkY2-Hqai066XWsCY4QAdwA9ixRVBxaaXdqrUjQJB2VCZMQocBY2BSMAcFBQvROABrFD06ndEXdQhQbqy+WGtKFojdfUKpUVovdCC2+2V4ue4Q+-0FboYWiR6D0ngQBPEJMp3ChITAegCHMxuOsEdjjD7BJHaCWLicRjQfGE4lQPkQRlCqQix3qqVAusqoNqkPmsPuixwZMAC399AAXrML6a9HIhgKFaFhsCwvqqHUni3sGfxXtawC+lBEAwl8yz3nBwGjECwgfsAwh-phaAgdIuG+vhNQFPQGTENwqEtOhJpEYC1psBQ5DggAblujDnIRkpYdoEbgBuPHEBAsbxomyapumWYoJunDbuJeYFg2N6tt0r7AB+Hg-t2DZgRByGaWR+GaWxlBcWJ5w9n2IlWGJEBDkuMkTlOM7kApNnTr6xCSYu0nACuyJrmy9i+qQTAsCAnL7rymLHgKRSnlA553kxAnEc+0g3vxZpapawx7DQ-YnJF0UgAFLCueOaYZtmEVRe4ICqQZVYab2pUOU1lUuUFskebOvUtdVtUhSyqKiUpvG+cQcXcgeR4nta6WwVlJFlBVLU1GtGEbTlUjcTNSrVPl8Ggex1knXxGVOv8gklWVinKVU9B+WNA0Tg13k3XNbWaZw20xbt7XFsdr3VBZV01BDs2zHZ3VRi9s3vcQ-Wjm5aZDV5KOnWjn2Y8Fq6ssc9iJQtPKHolK0WHtmUPdlQLTMw+UbAM2yHcCwPgvT90XdI-DXARd2Xo9FgFM8b7pOdWFPT1iWE2Osk-eT1wAw2LMQIDPOg4DiXCJpktVNLhtdWVavOcOX3YzVnkoJbSvJhgQA)
